modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId= "cataclysm" #mandatory
version="1.0" #mandatory
 # A display name for the mod
displayName="Cataclysm Mod" #mandatory
credits="dogulkkun,0dyss2y,mango03034,HedwigOwls" #optional
authors="L_Ender" #optional
description='''
Hello
EnderGuardian Theme made by Ean Grimm
https://www.tubersongs.com/
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.cataclysm]] #optional
    # the modid of the dependency
modId="citadel" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[1.8.0,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="AFTER"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
[[dependencies.cataclysm]]
modId="forge"
mandatory=true
versionRange="[36.0.42,)"
ordering="NONE"
side="BOTH"
